### ISSUE TITLE
实际运行下来，输出显示是有下载种子文件的，但是磁盘上没有

### ISSUE THREAD

**Issue by winglight** [zhangjh/islandBeauty#1]
输出如下：
`http://search.hdwan.net/cse/search?s=11504240492176070054&q=%E5%8F%98%E5%BD%A2%E9%87%91%E5%88%9A
http://www.hdwan.net/4263.html
[2014][美国][科幻][变形金刚4:绝迹重生][MKV/5.75G高清下载][中...
href:http://img.hdwan.net/2014/09/变形金刚4：绝迹重生.5.75GB.torrent
href:http://img.hdwan.net/2014/09/Transformers.Age_.of_.Extinction.2014.720p.torrent
curl http://img.hdwan.net/2014/09/变形金刚4：绝迹重生.5.75GB.torrent -o ../dst/movie/变形金刚4：绝迹重生575GB.torrent
curl http://img.hdwan.net/2014/09/Transformers.Age_.of_.Extinction.2014.720p.torrent -o ../dst/movie/中字版TransformersAgeofExtinction2014720pBDRMVB32G.torrent
`
但是，磁盘上连dist目录都没有创建，手动创建了目录也没用效果

**Comment by zhangjh** [comment]
你先在bin目录下手工执行下这条命令看有没有用？如果可以那么之前运行的时候有没有报错信息？给的信息不够不好排查
`curl http://img.hdwan.net/2014/09/Transformers.Age_.of_.Extinction.2014.720p.torrent -o ../dst/movie/中字版TransformersAgeofExtinction2014720pBDRMVB32G.torrent`

**Comment by winglight** [comment]
`Warning: Failed to create the file 
Warning: ../dst/movie/中字版TransformersAgeofExtinction2014720pBDRMVB32G.tor
Warning: rent: No such file or directory
curl: (23) Failed writing body (0 != 2671)`
这是没写入权限的意思吗？

我试了一下把../dst/movie/这段路径去掉就可以正常下载了

> 我发现我手工创建的目录是dist，当我把它改名为dst后，可以正常下载了

**Comment by zhangjh** [comment]
能提供下你的运行环境吗？这个错误是下载路径不识别

**Comment by winglight** [comment]
node: v5.10.1
OS: MacOS
这应该就是下载目录需要手工创建，没有自动创建产生的问题，直接写文件时，是不会自动创建目录的

**Comment by zhangjh** [comment]
代码已经更新，已经增加了自动创建目的目录的逻辑

**Comment by winglight** [comment]
测试了一下，已经可以自动创建目录了
