### ISSUE TITLE
电影天堂被封了，下载电影种子的路断了一条

### ISSUE THREAD

**Issue by zhangjh** [zhangjh/islandBeauty#2]
下载电影种子目前是有两个来源：
1. 海盗湾中文网
2. 电影天堂

电影天堂本来是资源主力，种子多，海盗湾资源不够多。但电影天堂最近被封了，还没有找到合适的替代源。不知道小伙伴们有没有好用的种子站？

**Comment by kevin-xk** [comment]
ed2000 资源共享，之前还有个迅播影院，貌似也被封了，你可以试试……

**Comment by zhangjh** [comment]
http://www.ed2kers.com/
先在此记录一下，这个网站还不错，资源够多。有空了改写下项目。

**Comment by yuanjinzhao** [comment]
国内资源太少了，各种连不上。有新的资源不

**Comment by zhangjh** [comment]
@yuanjinzhao 你有没有合适的种子站？现在国内种子站生存下来的不多了，有也是资源比较少或者旧的。。除非下高清之类还有需求否则现在下载下来再看的模式看来真的是被淘汰了。。
